name: build and tests

on:
    - push
    - pull_request

jobs:
    midynet-tests:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                    python-version: 3.9

            - name: Loading submodules
              shell: bash
              run: |
                    git submodule init
                    git submodule update

            - name: Install C++ dependencies
              shell: bash
              run: sudo apt install gcc-9 g++ cmake

            - name: Installing basegraph==1.0.0
              shell: bash
              run: |
                    cd _midynet/base_graph
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    cd ..
                    pip install .

            - name: Installing SamplableSet==2.2.0
              shell: bash
              run: |
                    echo Installing SamplableSet==2.2.0
                    cd _midynet/SamplableSet/src
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    cd ../..
                    pip install .

            - name: Building midynet backend and run c++ tests
              shell: bash
              run: |
                    echo Build backend and tests
                    cd _midynet
                    [ ! -d "./build" ] && mkdir build
                    cd build
                    cmake ..
                    make -j4
                    ctest -C Debug --output-on-failure --verbose

            - name: Installing dev-dependencies
              shell: bash
              run: |
                    pip install -r requirements_dev.txt
                    pip install -r requirements.txt
                    pip install pybind11

            - name: Installing midynet==0.0.1
              shell: bash
              run: |
                    [ -d "./build" ] && rm -r build
                    pip install .[testing]

            - name: Run tests
              shell: bash
              run: pytest
